### ISSUE TITLE
"CONTRACT_VALIDATE_ERROR"

### ISSUE THREAD

**Issue by jos89** [Fenguoz/tron-php#19]
Hello, when I try to invoke getTRC20 () -> transfer() I always get this error: "CONTRACT_VALIDATE_ERROR" Transfer Fail.

my current: 'contract_address' => 'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t'

What could be the problem? did i read maybe i should include bandwidth? how can I do?

thank you

**Comment by jos89** [comment]
Message is: CONTRACT_VALIDATE_ERROR  -> Contract validate error : account does not exist
What account are we talking about? the sender owns 18USDT ( THHtzyyQdCWvrLad9wZ9aA2yBuNsy1WerD ) from balance and the recipient has others. I use the privatekey for the sender, the one returned in the creation through GenerateAddress().
So the problem is TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t?

**Comment by Hateem76** [comment]
> Hello, when I try to invoke getTRC20 () -> transfer() I always get this error: "CONTRACT_VALIDATE_ERROR" Transfer Fail.
> 
> my current: 'contract_address' => 'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t'
> 
> What could be the problem? did i read maybe i should include bandwidth? how can I do?
> 
> thank you

how did you solve it then?
