### ISSUE TITLE
iexbase/tron-api 版本兼容性问题

### ISSUE THREAD

**Issue by 619096932** [Fenguoz/tron-php#2]
目前我测试到的  如果需要trc20转账 需要一下组合才可以

"require": {
        "iexbase/tron-api": "2.*",
        "fenguoz/tron-php": "0.1.4"
    },

原因是tron-api里面的一些方法有变更  比如 setIsOnlineSign 这个方法早就移除了  其他的还没测试

**Comment by Fenguoz** [comment]
确实存在该问题。版本3.0相比2.0移除了setIsOnlineSign()方法，3.0后仅支持离线签名。
已修改更新了 [tag0.1.9](https://github.com/Fenguoz/tron-php/releases/tag/0.1.9)

**Comment by LisenH** [comment]
trc20-USDT现在可以实现转账了吗？

**Comment by Fenguoz** [comment]
> trc20-USDT现在可以实现转账了吗？

可以

**Comment by LisenH** [comment]
> > trc20-USDT现在可以实现转账了吗？
> 
> 可以

大佬能否给个简明的代码例子？

**Comment by Fenguoz** [comment]
> > > trc20-USDT现在可以实现转账了吗？
> > 
> > 
> > 可以
> 
> 大佬能否给个简明的代码例子？

https://github.com/Fenguoz/tron-php/blob/dcdff26256d49e6e9b29300ac7aa1df650b0dd79/tests/TRC20Test.php#L71
