### ISSUE TITLE
Validate Transfer Contract Error when using $trxWallet->transfer($from,$to,$amount) method.

### ISSUE THREAD

**Issue by Hateem76** [Fenguoz/tron-php#20]
class org.tron.core.exception.ContractValidateException : Validate TransferContract error, no OwnerAccount.

**Comment by Yuxanju** [comment]
You will have to synchronize your wallet and make sure you debug it with bech13.

**Comment by hinego** [comment]
原因找到了 卡了我两个小时 出现这个问题是因为此地址尚未激活

只需要转任意一点点trx给这个地址激活就行了

**Comment by Hateem76** [comment]
Activate the addresses before sending any amounts. Activation is done by sending a transaction using your wallet.

**Comment by xiezh1010** [comment]
> 我也同样报了这个错 是交易TRX的时候 用测试的PRIVATE_KEY没有问题 但是如果换成自己的或者床架你的就会报这个错

兄弟，找到原因了吗，我用官方测试地址也不行

**Comment by ShaikhGaffar** [comment]
How can I Activate Account

**Comment by Hateem76** [comment]
have you solved it?
