### ISSUE TITLE
strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior

### ISSUE THREAD

**Issue by 619096932** [Fenguoz/tron-php#3]
Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior
[code] 8192 [type] Mix\Console\Exception\ErrorException
[file] in /Applications/code/ex/vendor/fenguoz/tron-php/src/Address.php on line 48

什么时候处理下哦。

**Comment by Fenguoz** [comment]
[处理strpos()不推荐提示](https://github.com/Fenguoz/tron-php/releases/tag/1.1.1)
