### ISSUE TITLE
support PHP8

### ISSUE THREAD

**Issue by sirosfakhri** [Fenguoz/tron-php#31]
hi there. is there any chance to upgrade this amazing package to PHP 8?

**Comment by Fenguoz** [comment]
Wait a minute. The related composer package is not compatible with PHP 8

**Comment by sirosfakhri** [comment]
> Wait a minute. The related composer package is not compatible with PHP 8

yep. Unfortunately, it seems so.
well, I think should wait to upgrade those.
by the way, thanks for your response.
