### ISSUE TITLE
generateAddress()，大家注意了，这个方法生成的钱包私钥跟地址不匹配。下面是我改写的方法

### ISSUE THREAD

**Issue by cww0128** [Fenguoz/tron-php#35]
/**
     * 生成钱包地址
     * 中文文档：https://tronapi.gitbook.io/trx/
     */
    public function generateAddress()
    {
        $tron = new \IEXBase\TronAPI\Tron();
        $generateAddress = $tron->generateAddress(); // or createAddress()
        $address = (array)($generateAddress)->getRawData();
        $retdata['privateKey'] = $address['private_key'];
        $retdata['address'] = $address['address_base58'];
        $retdata['hexAddress'] = $address['address_hex'];
        return json(['code' => 1, 'data' => $retdata]);
    }

**Comment by fuckwow** [comment]
非常感谢，不过也可以直接改原文
因为PHP8 所以返回是 ADDRESS类型
调整为

public function generateAddress(): Address
    {
        $attempts = 0;
        $validAddress = false;
        $tron = new \IEXBase\TronAPI\Tron();

        do {
            if ($attempts++ === 5) {
                throw new TronErrorException('Could not generate valid key');
            }


            $generateAddress = $tron->generateAddress(); // or createAddress()
            $address = (array)($generateAddress)->getRawData();
            $retdata['privateKey'] = $address['private_key'];
            $retdata['address'] = $address['address_base58'];
            $retdata['hexAddress'] = $address['address_hex'];
            $address = new Address($address['address_base58'], $address['private_key'], $address['address_hex']);
            $validAddress = $this->validateAddress($address);
        } while (!$validAddress);

        return $address;
    }

**Comment by yeshili** [comment]
php8.02无法安装改项目，头疼，老师提示版本出错 ！
