### ISSUE TITLE
安装最新版本的包，PHP 8.2.8 报错 已弃用:创建动态属性 麻烦解决一下谢谢

### ISSUE THREAD

**Issue by wangtao0135** [Fenguoz/tron-php#50]
Deprecated: Creation of dynamic property Tron\TRX::$_api is deprecated in /Users/work/test/vendor/fenguoz/tron-php/src/TRX.php on line 19

Deprecated: Creation of dynamic property Tron\TRX::$tron is deprecated in /Users/work/test/vendor/fenguoz/tron-php/src/TRX.php on line 26

Deprecated: Creation of dynamic property Tron\TRC20::$_api is deprecated in /Users/work/test/vendor/fenguoz/tron-php/src/TRX.php on line 19

Deprecated: Creation of dynamic property Tron\TRC20::$tron is deprecated in /Users/work/test/vendor/fenguoz/tron-php/src/TRX.php on line 26

Deprecated: Creation of dynamic property Tron\TRC20::$decimals is deprecated in /Users/work/test/vendor/fenguoz/tron-php/src/TRC20.php on line 25
object(Tron\Address)#157 (3) { ["privateKey"]=> string(66) "0xea28cbfd90582a6379223aacdd86db797a92d988ab79daac780a9f79586bce0b" ["address"]=> string(34) "TJeFsgJEkbwpim2C2gf1My2TLqCU6uhbFa" ["hexAddress"]=> string(42) "415f23a077db080f4f0f3c22e250557d46590d64f8" }

**Comment by Fenguoz** [comment]
已解决，请更新最新包
