### ISSUE TITLE
请教一下：我想做一个类似平台充值的功能，但是无从下手

### ISSUE THREAD

**Issue by you19891003** [Fenguoz/tron-php#6]
我现在已经有了一个账号，需要接收ABC 3人的充值，但是对于入账的金额，我并不知道是ABC中的谁充值进来的。
看官网，好像得利用这个来实现： https://api.shasta.trongrid.io/wallet/createaccount

谢谢作者大大！

**Comment by Fenguoz** [comment]
这属于具体业务了，这得看需求。一般充值会涉及到地址，充值监控，归集等功能。

**Comment by you19891003** [comment]
归集是怎么实现呀？官方有现成的API接口吗？

**Comment by you19891003** [comment]
感谢，谢谢大佬

**Comment by nblaoliu2022** [comment]
充值以及写好了一套，每个订单分配一个地址，秒级回调。联系我沟通  https://t.me/laowu2021

基于当前SDK最新版本波场支付php代码请看这里： https://tronapi.gitbook.io/trx/

也有写归集的框架（助记词归集以及私钥归集）

欢迎加飞机讨论 https://t.me/laowu2021
Tronapi_v2功能清单如下所示(trc20)：
1.生成钱包地址
2.生成带助记词的钱包地址
3.获取USDT余额
4.获取TRX余额
5.查询订单详情
6.私钥获取地址
7.助记词转私钥
8.查询最新区块
9.根据区块链查询信息
10.USDT交易转账
11.TRX交易转账（可添加备注）
12.查询最新交易（USDT）
13.TRC10转账
