### ISSUE TITLE
TRX转账没有使用离线签名吗?

### ISSUE THREAD

**Issue by 619096932** [Fenguoz/tron-php#7]
[Error.php:225] Client error: `POST https://api.trongrid.io/wallet/gettransactionsign` resulted in a `404 Not Found` response:
Error: 404 - Status: Not Found

[code] 404 [type] GuzzleHttp\Exception\ClientException
[file] in /Applications/code/ex/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113
 #0 GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) in /Applications/code/ex/vendor/guzzlehttp/guzzle/src/Middleware.php on line 65

**Comment by Fenguoz** [comment]
这个是由于`iexbase/tron-api`包处理的。现在rpc已经取消了在线签名。在3.1之前是有在线签名和离线签名，3.1就开始只有离线签名了。建议把`iexbase/tron-api`更新至3.1版本

**Comment by 619096932** [comment]
好吧。昨晚还自己搞了个离线签名 签名方法和以太坊的基本一致
